services:
    account:
        class: AppBundle\Service\AccountService
        arguments: ["@doctrine.orm.entity_manager"]
        calls:
            - [ setEncoder, ["@security.password_encoder"] ]
    form:
        class: AppBundle\Service\FormService
        arguments: ["@doctrine.orm.entity_manager"]